server:
  port: 9517
  context-path: /user

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9000/eureka


logging:
  level:
    com.chuenyee: debug

validateQuery: SELECT 1
spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    #mysql8:0     com.mysql.cj.jdbc.Driver  
    #mysql5.0     com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.196.156/gpwdb?userSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    #mysql5.0     jdbc:mysql://111.230.210.85:3306/mystorebase
    #mysql8:0  jdbc:mysql://111.230.210.85:3306/mystorebase?userSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT
    #?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: Jcy`916458927
  application:
    name: userServer





redis: 
  hostName: 127.0.0.1
  port: 6379
  maxIdle: 300
  maxTotal: 1000
  maxWaitMillis: 1000
  minEvictableIdleTimeMillis: 300000
  numTestsPerEvictionRun: 1024
  timeBetweenEvictionRunsMillis: 30000
  testOnBorrow: true
  testWhileIdle: true    
    
 